version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: actix_db
    environment:
      POSTGRES_DB: actix
      POSTGRES_USER: actix_user
      POSTGRES_PASSWORD: actix_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
